"""Tests for stopwords vocabulary extraction and sync."""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from reporails_cli.core.stopwords import (
    PatternParts,
    _split_alternation,
    _strip_flags,
    decompose,
    extract_vocab,
    is_guard,
    recompose,
)
from reporails_cli.core.stopwords_sync import check_staleness, sync_vocab

# ── decompose / recompose ────────────────────────────────────────────


class TestDecompose:
    @pytest.mark.parametrize(
        "pattern, expected_flags, expected_prefix, expected_terms, expected_suffix",
        [
            # Simple alternation
            ("(?:a|b|c)", "", "", ["a", "b", "c"], ""),
            # With flags
            ("(?i)(?:foo|bar)", "(?i)", "", ["foo", "bar"], ""),
            # With word boundaries
            (r"\b(?:x|y|z)\b", "", r"\b", ["x", "y", "z"], r"\b"),
            # Capturing group
            ("(MUST NOT?|NEVER|ALWAYS)", "", "", ["MUST NOT?", "NEVER", "ALWAYS"], ""),
            # Flags + boundaries
            (r"(?i)\b(?:error|fail)\b", "(?i)", r"\b", ["error", "fail"], r"\b"),
            # Regex terms with char classes
            ("(?:auto[- ]?generated|do not edit)", "", "", ["auto[- ]?generated", "do not edit"], ""),
            # Complex prefix/suffix
            (r"(?i)^[\s*>-]*(?:always|never).{10,}", "(?i)", r"^[\s*>-]*", ["always", "never"], ".{10,}"),
        ],
    )
    def test_decompose_patterns(
        self,
        pattern: str,
        expected_flags: str,
        expected_prefix: str,
        expected_terms: list[str],
        expected_suffix: str,
    ) -> None:
        parts = decompose(pattern)
        assert parts is not None, f"Failed to decompose: {pattern}"
        assert parts.flags == expected_flags
        assert parts.prefix == expected_prefix
        assert parts.terms == expected_terms
        assert parts.suffix == expected_suffix

    def test_decompose_returns_none_for_no_alternation(self) -> None:
        assert decompose(r"^---\n") is None

    def test_decompose_returns_none_for_single_term_group(self) -> None:
        assert decompose("(?:single)") is None

    def test_decompose_nested_groups_in_terms(self) -> None:
        """Terms can contain nested groups — they're regex fragments."""
        parts = decompose(r"(?:(?:confirm|ask)\s+before|risky|dangerous)")
        assert parts is not None
        assert len(parts.terms) == 3
        assert parts.terms[0] == r"(?:confirm|ask)\s+before"
        assert parts.terms[1] == "risky"

    def test_decompose_terms_with_char_classes(self) -> None:
        parts = decompose("(?:AKIA[A-Z0-9]{12,}|ghp_[A-Za-z0-9]{20,})")
        assert parts is not None
        assert parts.terms == ["AKIA[A-Z0-9]{12,}", "ghp_[A-Za-z0-9]{20,}"]

    def test_decompose_escaped_pipe_not_split(self) -> None:
        parts = decompose(r"(?:a\|b|c)")
        assert parts is not None
        assert parts.terms == [r"a\|b", "c"]


class TestRecompose:
    def test_round_trip_simple(self) -> None:
        original = "(?i)(?:foo|bar|baz)"
        parts = decompose(original)
        assert parts is not None
        assert recompose(parts) == original

    def test_round_trip_with_boundaries(self) -> None:
        original = r"(?i)\b(?:error|fail|crash)\b"
        parts = decompose(original)
        assert parts is not None
        assert recompose(parts) == original

    def test_recompose_with_new_terms(self) -> None:
        parts = PatternParts(
            flags="(?i)",
            prefix=r"\b",
            group_open="(?:",
            terms=["old"],
            suffix=r"\b",
        )
        result = recompose(parts, ["new1", "new2"])
        assert result == r"(?i)\b(?:new1|new2)\b"

    @pytest.mark.parametrize(
        "pattern",
        [
            "(?i)(?:TODO:\\s|FIXME:\\s|HACK:\\s|XXX:\\s|TEMP:\\s)",
            r"\b(MUST NOT?|NEVER|ALWAYS|REQUIRED|PROHIBITED|CRITICAL)\b",
            "(?i)(?:auto[- ]?generated|do not edit|generated by|template default)",
            r"(?i)\b(?:error|exception|fail|crash|retry|fallback)\b",
        ],
    )
    def test_round_trip_real_patterns(self, pattern: str) -> None:
        parts = decompose(pattern)
        assert parts is not None
        assert recompose(parts) == pattern


# ── _strip_flags / _split_alternation / is_guard ─────────────────────


class TestHelpers:
    def test_strip_flags_single(self) -> None:
        flags, rest = _strip_flags("(?i)abc")
        assert flags == "(?i)"
        assert rest == "abc"

    def test_strip_flags_multiple(self) -> None:
        flags, rest = _strip_flags("(?i)(?s)abc")
        assert flags == "(?i)(?s)"
        assert rest == "abc"

    def test_strip_flags_none(self) -> None:
        flags, rest = _strip_flags("abc")
        assert flags == ""
        assert rest == "abc"

    def test_split_alternation_simple(self) -> None:
        assert _split_alternation("a|b|c") == ["a", "b", "c"]

    def test_split_alternation_nested_groups(self) -> None:
        result = _split_alternation("(?:a|b)|c")
        assert result == ["(?:a|b)", "c"]

    def test_split_alternation_char_class(self) -> None:
        result = _split_alternation("[a|b]|c")
        assert result == ["[a|b]", "c"]

    def test_is_guard_true(self) -> None:
        assert is_guard(r"(?s)\A[\s\S]+")

    def test_is_guard_false(self) -> None:
        assert not is_guard("(?i)(?:foo|bar)")


# ── extract_vocab ────────────────────────────────────────────────────


class TestExtractVocab:
    def _write_checks(self, rule_dir: Path, checks: list[dict]) -> None:
        checks_path = rule_dir / "checks.yml"
        checks_path.write_text(yaml.dump({"checks": checks}), encoding="utf-8")

    def test_extract_standalone_pattern_regex(self, tmp_path: Path) -> None:
        self._write_checks(
            tmp_path,
            [
                {
                    "id": "X.0001.has_terms",
                    "type": "deterministic",
                    "pattern-regex": "(?i)(?:foo|bar|baz)",
                },
            ],
        )
        vocab = extract_vocab(tmp_path)
        assert vocab is not None
        assert vocab["has_terms"] == ["foo", "bar", "baz"]

    def test_extract_mechanical_content_absent(self, tmp_path: Path) -> None:
        self._write_checks(
            tmp_path,
            [
                {
                    "id": "X.0001.fast_check",
                    "type": "mechanical",
                    "check": "content_absent",
                    "args": {"pattern": "(?:a|b|c)"},
                },
            ],
        )
        vocab = extract_vocab(tmp_path)
        assert vocab is not None
        assert vocab["fast_check"] == ["a", "b", "c"]

    def test_extract_patterns_array_with_guard(self, tmp_path: Path) -> None:
        self._write_checks(
            tmp_path,
            [
                {
                    "id": "X.0001.find_keywords",
                    "type": "deterministic",
                    "patterns": [
                        {"pattern-regex": r"(?s)\A[\s\S]+"},
                        {"pattern-not-regex": r"\b(MUST|NEVER|ALWAYS)\b"},
                    ],
                },
            ],
        )
        vocab = extract_vocab(tmp_path)
        assert vocab is not None
        assert vocab["find_keywords"] == ["MUST", "NEVER", "ALWAYS"]

    def test_extract_patterns_array_both_extractable(self, tmp_path: Path) -> None:
        self._write_checks(
            tmp_path,
            [
                {
                    "id": "X.0001.dual_check",
                    "type": "deterministic",
                    "patterns": [
                        {"pattern-regex": r"(?i)\b(?:push|deploy|delete)\b"},
                        {"pattern-not-regex": "(?i)(?:risky|dangerous)"},
                    ],
                },
            ],
        )
        vocab = extract_vocab(tmp_path)
        assert vocab is not None
        # Multiple patterns → nested dict
        assert isinstance(vocab["dual_check"], dict)
        assert vocab["dual_check"]["pattern-regex"] == ["push", "deploy", "delete"]
        assert vocab["dual_check"]["pattern-not-regex"] == ["risky", "dangerous"]

    def test_extract_skips_semantic(self, tmp_path: Path) -> None:
        self._write_checks(
            tmp_path,
            [
                {"id": "X.0001.eval_quality", "type": "semantic"},
            ],
        )
        vocab = extract_vocab(tmp_path)
        assert vocab is None

    def test_extract_skips_no_alternation(self, tmp_path: Path) -> None:
        self._write_checks(
            tmp_path,
            [
                {
                    "id": "X.0001.single_pattern",
                    "type": "deterministic",
                    "pattern-regex": "^---\\n",
                },
            ],
        )
        vocab = extract_vocab(tmp_path)
        assert vocab is None

    def test_extract_no_checks_yml(self, tmp_path: Path) -> None:
        assert extract_vocab(tmp_path) is None


# ── sync_vocab ───────────────────────────────────────────────────────


class TestSyncVocab:
    def _setup_rule(
        self,
        rule_dir: Path,
        checks: list[dict],
        vocab: dict,
    ) -> None:
        (rule_dir / "checks.yml").write_text(yaml.dump({"checks": checks}), encoding="utf-8")
        (rule_dir / "vocab.yml").write_text(
            yaml.dump(vocab, default_flow_style=False, sort_keys=False),
            encoding="utf-8",
        )

    def _read_checks(self, rule_dir: Path) -> list[dict]:
        data = yaml.safe_load((rule_dir / "checks.yml").read_text(encoding="utf-8"))
        return data.get("checks", [])

    def test_sync_standalone_pattern_regex(self, tmp_path: Path) -> None:
        self._setup_rule(
            tmp_path,
            checks=[
                {
                    "id": "X.0001.has_terms",
                    "type": "deterministic",
                    "pattern-regex": "(?i)(?:foo|bar)",
                }
            ],
            vocab={"has_terms": ["foo", "bar", "baz"]},
        )
        result = sync_vocab(tmp_path)
        assert result.updated == 1

        checks = self._read_checks(tmp_path)
        assert checks[0]["pattern-regex"] == "(?i)(?:foo|bar|baz)"

    def test_sync_mechanical_content_absent(self, tmp_path: Path) -> None:
        self._setup_rule(
            tmp_path,
            checks=[
                {
                    "id": "X.0001.fast",
                    "type": "mechanical",
                    "check": "content_absent",
                    "args": {"pattern": "(?:a|b)"},
                }
            ],
            vocab={"fast": ["a", "b", "c"]},
        )
        result = sync_vocab(tmp_path)
        assert result.updated == 1

        checks = self._read_checks(tmp_path)
        assert checks[0]["args"]["pattern"] == "(?:a|b|c)"

    def test_sync_patterns_array_guard_plus_vocab(self, tmp_path: Path) -> None:
        self._setup_rule(
            tmp_path,
            checks=[
                {
                    "id": "X.0001.kw",
                    "type": "deterministic",
                    "patterns": [
                        {"pattern-regex": r"(?s)\A[\s\S]+"},
                        {"pattern-not-regex": r"\b(MUST|NEVER)\b"},
                    ],
                }
            ],
            vocab={"kw": ["MUST", "NEVER", "ALWAYS"]},
        )
        result = sync_vocab(tmp_path)
        assert result.updated == 1

        checks = self._read_checks(tmp_path)
        entry = checks[0]["patterns"][1]
        assert entry["pattern-not-regex"] == r"\b(MUST|NEVER|ALWAYS)\b"

    def test_sync_nested_format(self, tmp_path: Path) -> None:
        self._setup_rule(
            tmp_path,
            checks=[
                {
                    "id": "X.0001.dual",
                    "type": "deterministic",
                    "patterns": [
                        {"pattern-regex": r"(?i)\b(?:push|deploy)\b"},
                        {"pattern-not-regex": "(?i)(?:risky|dangerous)"},
                    ],
                }
            ],
            vocab={
                "dual": {
                    "pattern-regex": ["push", "deploy", "delete"],
                    "pattern-not-regex": ["risky", "dangerous", "irreversible"],
                },
            },
        )
        result = sync_vocab(tmp_path)
        assert result.updated == 1

        checks = self._read_checks(tmp_path)
        assert checks[0]["patterns"][0]["pattern-regex"] == r"(?i)\b(?:push|deploy|delete)\b"
        assert checks[0]["patterns"][1]["pattern-not-regex"] == "(?i)(?:risky|dangerous|irreversible)"

    def test_sync_no_change_when_terms_match(self, tmp_path: Path) -> None:
        self._setup_rule(
            tmp_path,
            checks=[
                {
                    "id": "X.0001.same",
                    "type": "deterministic",
                    "pattern-regex": "(?:a|b)",
                }
            ],
            vocab={"same": ["a", "b"]},
        )
        result = sync_vocab(tmp_path)
        assert result.updated == 0
        assert result.skipped == 1

    def test_sync_dry_run_does_not_write(self, tmp_path: Path) -> None:
        self._setup_rule(
            tmp_path,
            checks=[
                {
                    "id": "X.0001.t",
                    "type": "deterministic",
                    "pattern-regex": "(?:a|b)",
                }
            ],
            vocab={"t": ["a", "b", "c"]},
        )
        original = (tmp_path / "checks.yml").read_text(encoding="utf-8")
        sync_vocab(tmp_path, dry_run=True)
        assert (tmp_path / "checks.yml").read_text(encoding="utf-8") == original

    def test_sync_missing_check_suffix(self, tmp_path: Path) -> None:
        self._setup_rule(
            tmp_path,
            checks=[
                {
                    "id": "X.0001.existing",
                    "type": "deterministic",
                    "pattern-regex": "(?:a|b)",
                }
            ],
            vocab={"nonexistent": ["x", "y"]},
        )
        result = sync_vocab(tmp_path)
        assert result.skipped == 1
        assert any("nonexistent" in m for m in result.messages)

    def test_sync_preserves_wrapper(self, tmp_path: Path) -> None:
        """Sync preserves flags, prefix, suffix from the original pattern."""
        self._setup_rule(
            tmp_path,
            checks=[
                {
                    "id": "X.0001.bounded",
                    "type": "deterministic",
                    "pattern-regex": r"(?i)\b(?:old1|old2)\b",
                }
            ],
            vocab={"bounded": ["new1", "new2", "new3"]},
        )
        sync_vocab(tmp_path)
        checks = self._read_checks(tmp_path)
        assert checks[0]["pattern-regex"] == r"(?i)\b(?:new1|new2|new3)\b"


# ── Round-trip: extract → sync ──────────────────────────────────────


class TestRoundTrip:
    @pytest.mark.parametrize(
        "original_pattern",
        [
            "(?i)(?:TODO:\\s|FIXME:\\s|HACK:\\s|XXX:\\s|TEMP:\\s)",
            r"(?i)\b(?:error|exception|fail|crash|retry|fallback)\b",
            r"\b(MUST NOT?|NEVER|ALWAYS|REQUIRED|PROHIBITED|CRITICAL)\b",
            "(?i)(?:auto[- ]?generated|do not edit|generated by|placeholder)",
        ],
    )
    def test_extract_then_sync_preserves_pattern(self, tmp_path: Path, original_pattern: str) -> None:
        """Extract terms, then sync them back — pattern should be identical."""
        checks = [
            {
                "id": "X.0001.roundtrip",
                "type": "deterministic",
                "pattern-regex": original_pattern,
            }
        ]
        (tmp_path / "checks.yml").write_text(yaml.dump({"checks": checks}), encoding="utf-8")

        # Extract
        vocab = extract_vocab(tmp_path)
        assert vocab is not None
        (tmp_path / "vocab.yml").write_text(
            yaml.dump(vocab, default_flow_style=False, sort_keys=False),
            encoding="utf-8",
        )

        # Sync — should not change anything since terms are identical
        result = sync_vocab(tmp_path)
        assert result.updated == 0  # No change expected

        # Verify pattern is unchanged
        data = yaml.safe_load((tmp_path / "checks.yml").read_text(encoding="utf-8"))
        assert data["checks"][0]["pattern-regex"] == original_pattern


# ── Staleness detection ──────────────────────────────────────────────


class TestStaleness:
    def test_stale_when_terms_differ(self, tmp_path: Path) -> None:
        (tmp_path / "checks.yml").write_text(
            yaml.dump(
                {
                    "checks": [
                        {
                            "id": "X.0001.check",
                            "type": "deterministic",
                            "pattern-regex": "(?:a|b)",
                        }
                    ]
                }
            ),
            encoding="utf-8",
        )
        (tmp_path / "vocab.yml").write_text(
            yaml.dump({"check": ["a", "b", "c"]}),
            encoding="utf-8",
        )
        result = check_staleness(tmp_path)
        assert result is not None
        assert result.stale is True

    def test_not_stale_when_terms_match(self, tmp_path: Path) -> None:
        (tmp_path / "checks.yml").write_text(
            yaml.dump(
                {
                    "checks": [
                        {
                            "id": "X.0001.check",
                            "type": "deterministic",
                            "pattern-regex": "(?:a|b)",
                        }
                    ]
                }
            ),
            encoding="utf-8",
        )
        (tmp_path / "vocab.yml").write_text(
            yaml.dump({"check": ["a", "b"]}),
            encoding="utf-8",
        )
        result = check_staleness(tmp_path)
        assert result is not None
        assert result.stale is False

    def test_no_vocab_returns_none(self, tmp_path: Path) -> None:
        assert check_staleness(tmp_path) is None
