"""Hedge phrases (`where possible`, `It's best (not) to`) and noun-initial declaratives.

- An instruction carrying `where possible`, `if possible`, `when possible` or `whenever possible`
  reads hedged; `as soon as possible` is urgency and does not.
- `It's best to <verb> …` is a hedged directive, `It's best not to <verb> …` a hedged constraint.
- A line that opens with a word that can also be a verb but starts the subject of a later verb
  (`Build artifacts live under dist/`) is a statement, not an instruction.
"""

from __future__ import annotations

import pytest

from reporails_cli.core.mapper.classify import (
    best_to_sign,
    classify_charge,
    has_hedge_cue,
    hedges_with_possible,
    starts_noun_subject,
)
from reporails_cli.core.mapper.instructions import instruction_count
from reporails_cli.core.mapper.parse import _apply_hedged_should_floor
from reporails_cli.core.platform.dto.ruleset import Atom


def _atom(text: str, cv: int, modality: str = "imperative") -> Atom:
    charge = {-1: "CONSTRAINT", 0: "NEUTRAL", 1: "DIRECTIVE"}[cv]
    return Atom(
        line=1,
        text=text,
        kind="excitation",
        charge=charge,
        charge_value=cv,
        modality=modality if cv else "none",
        specificity="abstract",
        plain_text=text,
        format="prose",
    )


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    ("text", "hedged"),
    [
        ("Delete the temporary files where possible.", True),
        ("Delete the temporary files if possible.", True),
        ("Delete the temporary files when possible.", True),
        ("Delete the temporary files whenever possible.", True),
        ("Delete the temporary files as soon as possible.", False),
        ("Delete the temporary files as much as possible.", False),
        ("Delete the temporary files as early as possible.", False),
        ("Delete the temporary files.", False),
    ],
)
def test_possible_hedges_only_with_where_if_when(text: str, hedged: bool) -> None:
    assert hedges_with_possible(text) is hedged
    modality = classify_charge(text)[2]
    assert (modality == "hedged") is hedged


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    ("text", "sign"),
    [
        ("It's best to regenerate `dist/` with `make build`.", 1),
        ("It is best to regenerate `dist/` with `make build`.", 1),
        ("It\u2019s best to regenerate `dist/` with `make build`.", 1),
        ("It's best not to edit files under `dist/` by hand.", -1),
        ("It is best not to edit files under `dist/` by hand.", -1),
        ("It's best to the left.", 0),
        ("It is best practice.", 0),
        ("That is best to regenerate.", 0),
    ],
)
def test_best_to_lead_carries_the_direction_of_its_instruction(text: str, sign: int) -> None:
    assert best_to_sign(text) == sign
    charge, value, modality, _trace, _scope = classify_charge(text)
    assert value == sign
    if sign:
        assert modality == "hedged"
        assert charge == ("DIRECTIVE" if sign > 0 else "CONSTRAINT")


@pytest.mark.unit
@pytest.mark.subsys_map
def test_the_hedge_floor_charges_a_best_to_statement_and_hedges_a_possible_instruction() -> None:
    best = _atom("It's best to regenerate `dist/` with `make build`.", 0)
    best_not = _atom("It's best not to edit files under `dist/` by hand.", -1, "direct")
    possible = _atom("Regenerate `dist/` after source changes where possible.", 1)
    urgent = _atom("Regenerate `dist/` as soon as possible.", 1)
    plain = _atom("The build is best done where possible.", 0)
    _apply_hedged_should_floor([best, best_not, possible, urgent, plain])
    assert (best.charge_value, best.modality) == (1, "hedged")
    assert (best_not.charge_value, best_not.modality) == (-1, "hedged")
    assert (possible.charge_value, possible.modality) == (1, "hedged")
    assert urgent.modality == "imperative"
    assert (plain.charge_value, plain.modality) == (0, "none")


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    "text",
    [
        "Build artifacts with `make`.",
        "Set timeouts to 30s.",
        "Cache responses for an hour.",
        "Test changes before merging.",
        "Build the image and push it.",
        "Run the build before committing.",
    ],
)
def test_an_order_that_opens_with_a_verb_stays_an_instruction(text: str) -> None:
    assert starts_noun_subject(text) is False
    assert classify_charge(text)[:2] == ("IMPERATIVE", 1)


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    "text",
    [
        "Set theory underlies the proof in this chapter.",
        "Cache misses slow the build down.",
        "Build artifacts live under `dist/`.",
        "Build artifacts are regenerated by CI.",
        "Cache keys are derived from the file hash.",
    ],
)
def test_a_statement_that_opens_with_a_noun_verb_homograph_reads_neutral(text: str) -> None:
    assert starts_noun_subject(text) is True
    assert classify_charge(text)[:2] == ("NEUTRAL", 0)


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    "text",
    [
        "Run `cleanup --where possible` before release.",
        "Run `make clean # if possible` before release.",
        "Run `cleanup --best` before release, it's fine.",
    ],
)
def test_a_hedge_phrase_inside_a_code_span_is_not_a_hedge(text: str) -> None:
    assert hedges_with_possible(text) is False
    assert classify_charge(text)[2] != "hedged"
    atom = _atom(text, 1)
    _apply_hedged_should_floor([atom])
    assert atom.modality == "imperative"


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    "text",
    [
        "Run the tests, then set NODE_ENV to production.",
        "Install deps and set CI=1.",
    ],
)
def test_a_packed_sentence_with_set_still_counts_two_instructions(text: str) -> None:
    assert instruction_count(text) == 2


@pytest.mark.unit
@pytest.mark.subsys_map
def test_set_as_an_opening_verb_is_not_ambiguous() -> None:
    charge, value, _modality, trace, _scope = classify_charge("Set NODE_ENV to production.")
    assert (charge, value) == ("IMPERATIVE", 1)
    assert "!amb" not in trace


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    ("text", "sign"),
    [
        ("It's best to avoid committing secrets.", -1),
        ("It's best to never push to main.", -1),
        ("It's best to not edit dist/ by hand.", -1),
        ("It is best to don't force-push.", -1),
        ("It's best to commit often.", 1),
    ],
)
def test_a_best_to_lead_before_a_prohibition_is_a_hedged_constraint(text: str, sign: int) -> None:
    assert best_to_sign(text) == sign
    charge, value, modality, _trace, _scope = classify_charge(text)
    assert (value, modality) == (sign, "hedged")
    assert charge == ("DIRECTIVE" if sign > 0 else "CONSTRAINT")
    atom = _atom(text, 0)
    _apply_hedged_should_floor([atom])
    assert (atom.charge_value, atom.modality) == (sign, "hedged")


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    "text",
    [
        "Start workers once tests exist.",
        "Split files whose names contain spaces.",
        "Start services while the cache warms.",
        "Split files which contain spaces.",
    ],
)
def test_an_order_whose_first_clause_ends_before_a_verb_stays_an_instruction(text: str) -> None:
    assert starts_noun_subject(text) is False
    assert classify_charge(text)[1] == 1


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    ("text", "hedged"),
    [
        ("Delete the temporary files wherever possible.", True),
        ("If possible, delete the temporary files.", True),
        ("Delete the temporary files (where possible).", True),
        ("Delete files where possible; keep the rest.", True),
        ("Check if possible duplicates exist before merging.", False),
        ("Check when possible conflicts arise.", False),
    ],
)
def test_possible_hedges_only_when_it_ends_the_clause(text: str, hedged: bool) -> None:
    assert hedges_with_possible(text) is hedged
    assert has_hedge_cue(text) is hedged
    assert (classify_charge(text)[2] == "hedged") is hedged


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    ("md", "plain", "hedged"),
    [
        ("Run `make where possible`", "Run make where possible", False),
        ("`It's best to` is a phrase we flag.", "It's best to is a phrase we flag.", False),
        ("Run `make build` where possible.", "Run make build where possible.", True),
        ("Run it **where possible**.", "Run it where possible.", True),
    ],
)
def test_the_lexical_entry_masks_code_spans_when_given_the_parsers_plain_text(
    md: str, plain: str, hedged: bool
) -> None:
    assert (classify_charge(md, plain_text=plain)[2] == "hedged") is hedged
    assert (classify_charge(md)[2] == "hedged") is hedged


@pytest.mark.unit
@pytest.mark.subsys_map
def test_the_hedge_floor_and_cue_read_the_markdown_that_keeps_its_code_spans() -> None:
    atom = _atom("Run `make where possible`.", 1)
    atom.plain_text = "Run make where possible."
    _apply_hedged_should_floor([atom])
    assert atom.modality == "imperative"
    assert has_hedge_cue("Run `make where possible`.") is False
    assert has_hedge_cue("Run it where possible.") is True


@pytest.mark.unit
@pytest.mark.subsys_map
@pytest.mark.parametrize(
    "text",
    [
        "Fix flaky tests you can reproduce",
        "Test changes you can reproduce locally",
        "Remove whatever is unused",
        "Test what you changed",
        "Fix how it works",
    ],
)
def test_a_pronoun_or_wh_word_after_the_opening_verb_ends_the_subject(text: str) -> None:
    assert starts_noun_subject(text) is False
